# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf3210d98f8faa5a7f89490075e51b4b7a7264aab710b0e8edc02415be2b6b6e2f068d1d43d961e13a338d07b8faaa88ad9a5feac6cf819eb0572740c73a842

test:
  secret_key_base: 20cce067986f1903b1c9ecf92d1378402591e9da9c1cab99e2c9accdc9d4bc6fbf81b29d4f5c415d697a47b8ee74edfd90dd82133cff89c7d109a094cc47006f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
